---
repos:
  - repo: local
    hooks:
      - id: python-install
        name: Install Python dependencies
        entry: mask development python install
        files: 'pyproject\.toml|uv\.lock'
        pass_filenames: false
        language: system
      - id: python-checks
        name: Check all Python code
        entry: mask development python checks
        files: '\.py$|pyproject\.toml|uv\.lock'
        pass_filenames: false
        language: system
        fail_fast: true
      - id: rust-checks
        name: Check all Rust code
        entry: mask development rust checks
        files: '\.rs$|Cargo\.(toml|lock)'
        pass_filenames: false
        language: system
        fail_fast: true
      - id: markdown-checks
        name: Check all Markdown code
        entry: mask development markdown checks
        pass_filenames: false
        types:
          - file
          - markdown
        language: system
        fail_fast: true
      - id: yaml-checks
        name: Check all YAML code
        entry: mask development yaml checks
        pass_filenames: false
        types:
          - file
          - yaml
        language: system
        fail_fast: true
