---
# yamllint disable rule:line-length
config:
  aws:region: us-east-1
  fund:budgetAlertEmailAddresses:
    secure: AAABAEVOj8Wk2uRR16QLK4GVV/0Q7NqIgcpgPSEGeWeIDeq2l9JANRiPzcqKk0HfPYnJ1+x+DR0GeVYwvSENSURnq/Or5Bc0pMqMYHyMFbXqXp45VE6J2XuyaUSF8WQK3IyNcJr7HAoK/9VtRrttbQ==
  fund:githubActionsRoleName: fund-github-actions-infrastructure-role
  fund:sagemakerExecutionRoleName: fund-sagemaker-execution-role
  fund:githubRepository: oscmcompany/fund
  fund:githubBranch: master
  fund:monthlyBudgetLimitUsd: "25"
  fund:githubWorkflowFiles:
    - launch_infrastructure.yaml
    - teardown_infrastructure.yaml
  fund:datamanagerSecretName:
    secure: AAABAETFtwN9i15kl2zVie22BRp5EkF3PBV0xwgNfu61tGsy0z4d9ZXa6hMZ6d2kBAssfYksqgPVZLA=
  fund:datamanagerSecretValue:
    secure: AAABAChRujETi2wJ+Tw2jj64uVvght6AMW5E+nuePkXqKXWyrMSVEIVQ5o9NRIHRRQ0wh1F3WzRW+BysSZhpdH/fULYOz9gtMmKlcG01uAApHdy8cWBk
  fund:portfoliomanagerSecretName:
    secure: AAABAKf+lbs+gJkBwQNt2mFUMhX/RnrgWwEFEaLwND4l8yeCTIrUa/guHH0bl22SllDrOm2yu/oYnKBa77AhVA==
  fund:portfoliomanagerSecretValue:
    secure: AAABAKW6YZV5HEHJBO04eh9QW/woEl/cvAgoDiURRH5e+YUwr+Muw6IR4hny+NQXrftQhk0EGS/E6OA1n9nElWqvjycm23MV/xR4CTlvW60CRQoQrOSWZuDdqmwv4KUa7qxVEZqYrPO86qJDBfXDIDJ5lkW8R1XmDR/+ubIV3nrkgvkEnXEtZWx1hzeXSsgfR7759Q0QXbSs8AfhGT8hxztiDxwDsSFQOA==
  fund:sharedSecretName:
    secure: AAABAN+AOhwp6jr/FKgLoyOBHVEeiG8kxzGJrsTr30gnj5JiuQs+YJmmFRSd0cdOHJotfJ8Y
  fund:sharedSecretValue:
    secure: AAABACKTBgsKXMGiDo/WXf5/WTwxHIKAKYUGOMhCecEe09+g/huViXxO1fYA+I2EdIcxBk8zerAoxkOGNUMkik+45skuj3vUYHraOLiKmzSt9h7Z1R56ixPoNMrTSbCMjpHOHZSji0G7lH2qCdCj6jGH/aouZjZRsnPLGa5/pxjhe+1aUtuvwLoqr6IlyuPEkw==
